[package]
name = "imc-hdf5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imc-rs = {path="../lib"}
ndarray = "0.15.6"


hdf5 = {version = "0.8.1"}

[features]
default = []
blosc = ["hdf5/blosc"]